SELECT 
    CASE
        WHEN GRADES.GRADE > 7 THEN STUDENTS.NAME
        WHEN GRADES.GRADE <= 7 THEN NULL
    END, GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS INNER JOIN GRADES 
ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME ASC, STUDENTS.MARKS ASC;
